import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "../providers";

export const metadata: Metadata = {
  title: "NextPay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
      <body>{children}</body> {/*  inter.children */}
      </Providers>
    </html>
  );
}
